/* Subset Japanese fonts, generated by components/fonts/generate.sh from
 * components/fonts/ui_strings.txt. Each contains ASCII plus exactly the
 * Japanese characters this UI displays. */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(lw_font_jp_16);
LV_FONT_DECLARE(lw_font_jp_24);

#ifdef __cplusplus
}
#endif
